name: lask_news_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  persistent_bottom_nav_bar: ^6.2.1
  another_flushbar: ^1.12.30
  font_awesome_flutter: ^10.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: