name: lask_news_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  path_provider: ^2.1.5
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.2
  weather: ^3.1.1
dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
